# Generated by Django 3.2.2 on 2021-08-05 03:36

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0002_alter_category_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='limit')),
                ('duration', models.DurationField(verbose_name='duration')),
                ('criterion', models.CharField(choices=[('>', 'More than ...'), ('<', 'Less than ...')], max_length=2, verbose_name='criterion')),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18, verbose_name='color')),
                ('creation_at', models.DateField(auto_now_add=True, verbose_name='creation_at')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='updated_at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='budget.category', verbose_name='category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Widget',
                'verbose_name_plural': 'Widgets',
            },
        ),
    ]
